###########################################################
#
# Simple Makefile for Operating Systems Project 2
# Thread Scheduling
#
###########################################################
.SUFFIXES: .cpp

vc: ScheduleYield.cpp
	g++ ScheduleYield.cpp -o vc -lpthread -std=c++11

clean:
	/bin/rm -f *.o *~ core vc



