###########################################################
#
# Simple Makefile for Operating Systems Project 2
# Fibonacci generator
#
###########################################################
.SUFFIXES: .cpp

fibonacci: Fibonacci.cpp
	g++ Fibonacci.cpp -o fibonacci -lpthread -std=c++11

clean:
	/bin/rm -f *.o *~ core fibonacci



