###########################################################
#
# Simple Makefile for Operating Systems Project 4
# Banker
#
###########################################################
.SUFFIXES: .cpp .h

banker: banker.cpp
	g++ banker.cpp -o banker -std=c++11

clean:
	/bin/rm -f *.o *~ core banker



